# Generated by Django 2.2.5 on 2019-09-03 00:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grupos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('dt_criacao', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos_contatos')),
                ('nome', models.CharField(max_length=100)),
                ('telefone1', models.CharField(max_length=11, null=True, unique=True)),
                ('telefone2', models.CharField(max_length=11, null=True, unique=True)),
                ('email1', models.EmailField(max_length=60, null=True, unique=True)),
                ('email2', models.EmailField(max_length=60, null=True, unique=True)),
                ('endereco', models.CharField(max_length=100, null=True)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Grupos')),
            ],
        ),
    ]
