# Generated by Django 2.2.5 on 2019-09-03 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contato',
            name='email2',
        ),
        migrations.RemoveField(
            model_name='contato',
            name='telefone2',
        ),
    ]
