# Generated by Django 2.2.5 on 2019-09-04 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190902_2205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contato',
            name='foto',
        ),
    ]
